<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountOfAllProducts()
    {
        $sql = $this->createQueryBuilder('p');
        $sql->select('COUNT(p.id)');
        return $sql->getQuery()->getSingleScalarResult();
    }

    public function getCountByCategory($category)
    {
        $sql = $this->createQueryBuilder('p');
        $sql->select('COUNT(p.id)')
            ->where('p.category = :name')
            ->setParameter('name', $category);
        return $sql->getQuery()->getSingleScalarResult();
    }
}
